# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=32, unique=True, verbose_name='区域')),
            ],
            options={
                'verbose_name_plural': '地区',
                'default_permissions': (),
                'permissions': (('view_area', '查看区域'), ('edit_area', '管理区域')),
                'verbose_name': '地区',
            },
        ),
        migrations.CreateModel(
            name='AssetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='平台名称')),
                ('address', models.CharField(max_length=200, verbose_name='平台地址')),
                ('people', models.CharField(max_length=32, verbose_name='商务联系人')),
                ('phone', models.IntegerField(verbose_name='联系电话')),
                ('QQ', models.IntegerField(verbose_name='联系QQ')),
                ('wechat', models.CharField(max_length=32, verbose_name='联系微信')),
                ('QQ_group', models.IntegerField(verbose_name='响应QQ群')),
                ('comment', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '云平台管理',
                'default_permissions': (),
                'permissions': (('view_cloud', '查看云平台'), ('edit_cloud', '管理云平台')),
                'verbose_name': '云平台管理',
            },
        ),
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_name', models.CharField(max_length=32, unique=True, verbose_name='数据库名称')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('type', models.SmallIntegerField(choices=[(1, 'MySQL'), (2, 'MongoDB'), (3, 'Memcached')], verbose_name='类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[(0, '上线'), (1, '下线')], default=0, verbose_name='设备状态')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Area', verbose_name='所在区域')),
                ('cloud_name', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cloud', verbose_name='所属云平台')),
            ],
            options={
                'verbose_name_plural': '数据库管理',
                'default_permissions': (),
                'permissions': (('view_database', '查看数据库'), ('edit_database', '管理数据库')),
                'verbose_name': '数据库管理',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('area', models.SmallIntegerField(choices=[('1', '大陆'), ('2', '日韩'), ('3', '欧美')], verbose_name='区域')),
                ('people', models.CharField(max_length=32, verbose_name='负责人')),
                ('comment', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '项目管理',
                'default_permissions': (),
                'permissions': (('view_project', '查看项目'), ('edit_project', '管理项目')),
                'verbose_name': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saltid', models.CharField(max_length=32, unique=True, verbose_name='SaltId')),
                ('hostname', models.CharField(blank=True, max_length=50, verbose_name='主机名')),
                ('lan_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('wan_ip', models.GenericIPAddressField(unique=True, verbose_name='外网ip')),
                ('osversion', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本')),
                ('memory', models.CharField(blank=True, max_length=50, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=32, null=True, verbose_name='硬盘')),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU型号')),
                ('cpu_core', models.SmallIntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('kernel', models.CharField(blank=True, max_length=50, null=True, verbose_name='内核')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.SmallIntegerField(choices=[('0', '上线'), ('1', '下线')], default=0, verbose_name='设备状态')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Area', verbose_name='所在区域')),
                ('cloud_name', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cloud', verbose_name='所属云平台')),
                ('project_name', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name_plural': '主机管理',
                'default_permissions': (),
                'permissions': (('view_server', '查看主机'), ('edit_server', '管理主机')),
                'verbose_name': '主机管理',
            },
        ),
        migrations.AddField(
            model_name='database',
            name='project_name',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='所属项目'),
        ),
    ]
