# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171205_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='QQ_group',
            field=models.CharField(max_length=32, verbose_name='响应QQ群'),
        ),
    ]
