# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171205_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.SmallIntegerField(choices=[(1, '大陆'), (2, '日韩'), (3, '欧美')], verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='server',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Area', verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '上线'), (1, '下线')], default=0, verbose_name='设备状态'),
        ),
    ]
