# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171208_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Area', verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '上线'), (2, '下线')], default=0, verbose_name='设备状态'),
        ),
    ]
