# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20171219_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='wan_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网ip'),
        ),
    ]
