# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20171219_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='操作系统'),
        ),
    ]
